#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
P2b_map_site_to_gene.py
Stage2b: Map CpG sites to nearest gene TSS (static gene context).

Input:
  P1 long table (site×cell):
    data/data_out/PBMC_CPG_ALL_UNION/ALL_cells_{union|intersection}_CpG_long_table.csv
  promoter BED:
    data/mouse_mm10_promoter_500bp.bed  (or your custom)

Output:
  long table + gene_id/gene_name/dist_to_TSS:
    data/data_out/Brain_CPG_ALL_UNION/ALL_cells_{mode}_CpG_long_table_with_gene.csv
"""

import os
import argparse
import numpy as np
import pandas as pd


def load_promoter_bed(promoter_bed_path: str) -> pd.DataFrame:
    """
    promoter BED: chrom  start  end  gene_id  gene_name  strand
    start/end: 0-based half-open
    TSS 1-based:
      +: tss = start + 500 (because your bed is TSS±500bp and end==tss0)
      -: tss = end   - 500
    If the BED is generated by your A1_GTF_to_TSS.py / A1_extract_promoters_fasta.py chain,
    this convention matches.
    """
    df = pd.read_csv(
        promoter_bed_path,
        sep="\t",
        header=None,
        names=["chrom", "start", "end", "gene_id", "gene_name", "strand"],
        low_memory=False
    )
    df["chrom"] = df["chrom"].astype(str).str.strip()
    df["start"] = pd.to_numeric(df["start"], errors="coerce")
    df["end"] = pd.to_numeric(df["end"], errors="coerce")
    df = df.dropna(subset=["chrom", "start", "end", "gene_id", "gene_name"]).copy()
    df["start"] = df["start"].astype(int)
    df["end"] = df["end"].astype(int)
    strand = df["strand"].astype(str).str.strip()

    # Compute a strand-aware representative TSS position (1-based)
    # If bed is exactly PROM_LEN upstream/downstream, then:
    #   + strand: tss0 = end, so tss_1based = end + 1
    #   - strand: tss0 = start, so tss_1based = start + 1
    # This is robust for your bed generation.
    tss_1based = np.where(strand == "-", df["start"].to_numpy() + 1, df["end"].to_numpy() + 1)
    df["tss_1based"] = tss_1based.astype(np.int64)
    return df


def build_tss_index(tss_df: pd.DataFrame) -> dict:
    """
    Build dict: chrom -> {pos: sorted positions, gene_id, gene_name}
    """
    chrom_to_tss = {}
    for chrom, subdf in tss_df.groupby("chrom", sort=False):
        sub = subdf.sort_values("tss_1based").reset_index(drop=True)
        chrom_to_tss[chrom] = {
            "pos": sub["tss_1based"].to_numpy(dtype=np.int64),
            "gene_id": sub["gene_id"].astype(str).to_numpy(dtype=object),
            "gene_name": sub["gene_name"].astype(str).to_numpy(dtype=object),
        }
    return chrom_to_tss


def assign_cpg_to_gene(cpg_sites: pd.DataFrame, chrom_to_tss: dict,
                       chrom_col: str, pos_col: str, max_distance: int = None) -> pd.DataFrame:
    """
    Input is UNIQUE site table (chrom,pos), output adds gene_id/gene_name/dist_to_TSS.
    """
    gene_ids, gene_names, dists = [], [], []

    chrom_vals = cpg_sites[chrom_col].astype(str).to_numpy()
    pos_vals = cpg_sites[pos_col].astype(int).to_numpy()

    total_sites = len(chrom_vals)
    for idx, (chrom, pos) in enumerate(zip(chrom_vals, pos_vals)):
        if idx % 100000 == 0 and idx > 0:
            print(f"   🔄 已处理 {idx:,}/{total_sites:,} 个位点")

        if chrom not in chrom_to_tss:
            gene_ids.append(np.nan)
            gene_names.append(np.nan)
            dists.append(np.nan)
            continue

        tss_info = chrom_to_tss[chrom]
        tss_pos = tss_info["pos"]

        # nearest neighbor by binary search
        j = np.searchsorted(tss_pos, pos)
        candidates = []
        if j > 0:
            candidates.append(j - 1)
        if j < len(tss_pos):
            candidates.append(j)

        best_i, best_dist = None, None
        for k in candidates:
            dist = abs(int(tss_pos[k]) - pos)
            if best_dist is None or dist < best_dist:
                best_dist = dist
                best_i = k

        if best_i is None:
            gene_ids.append(np.nan)
            gene_names.append(np.nan)
            dists.append(np.nan)
        elif (max_distance is not None) and (best_dist > max_distance):
            gene_ids.append(np.nan)
            gene_names.append(np.nan)
            dists.append(best_dist)
        else:
            gene_ids.append(tss_info["gene_id"][best_i])
            gene_names.append(tss_info["gene_name"][best_i])
            dists.append(best_dist)

    out = cpg_sites.copy()
    out["gene_id"] = gene_ids
    out["gene_name"] = gene_names
    out["dist_to_TSS"] = dists
    return out


def resolve_input(base_dir: str, mode: str, input_csv: str) -> str:
    if input_csv and input_csv.strip():
        return input_csv.strip()
    mode = mode.lower().strip()
    return os.path.join(base_dir, f"ALL_cells_{mode}_CpG_long_table.csv")


def resolve_output(base_dir: str, mode: str, out_csv: str) -> str:
    if out_csv and out_csv.strip():
        return out_csv.strip()
    mode = mode.lower().strip()
    return os.path.join(base_dir, f"ALL_cells_{mode}_CpG_long_table_with_gene.csv")


def main():
    ap = argparse.ArgumentParser(description="P2b: Map CpG sites to nearest gene (TSS)")
    ap.add_argument("--base_dir", default=r"data/data_out/PBMC_CPG_ALL_UNION")
    ap.add_argument("--input_mode", choices=["union", "intersection"], default="union")
    ap.add_argument("--input_csv", default="", help="optional manual long table path")
    ap.add_argument("--promoter_bed", default=r"data/human_hg38_promoter_500bp.bed")
    ap.add_argument("--out_csv", default="", help="optional output path")
    ap.add_argument("--chrom_col", default="chrom")
    ap.add_argument("--pos_col", default="pos_based")
    ap.add_argument("--max_tss_distance", type=int, default=None)

    args = ap.parse_args()

    in_path = resolve_input(args.base_dir, args.input_mode, args.input_csv)
    out_path = resolve_output(args.base_dir, args.input_mode, args.out_csv)

    if not os.path.exists(args.promoter_bed):
        raise FileNotFoundError(f"Promoter BED not found: {args.promoter_bed}")
    if not os.path.exists(in_path):
        raise FileNotFoundError(f"Long table not found: {in_path}")

    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)

    print("\n" + "=" * 80)
    print("🧬 P2b: Map CpG sites to nearest gene TSS")
    print("=" * 80)
    print(f"Input : {in_path}")
    print(f"BED   : {args.promoter_bed}")
    print(f"Output: {out_path}")

    print("\n[1/4] Loading promoter BED + building TSS index...")
    tss_df = load_promoter_bed(args.promoter_bed)
    chrom_to_tss = build_tss_index(tss_df)
    print(f"✅ TSS index built: {len(chrom_to_tss)} chromosomes")

    print("\n[2/4] Loading CpG long table...")
    cpg_df = pd.read_csv(in_path, low_memory=False)
    required = [args.chrom_col, args.pos_col]
    missing = [c for c in required if c not in cpg_df.columns]
    if missing:
        raise ValueError(f"Missing columns in long table: {missing}")

    cpg_df[args.chrom_col] = cpg_df[args.chrom_col].astype(str).str.strip()
    cpg_df[args.pos_col] = pd.to_numeric(cpg_df[args.pos_col], errors="coerce")
    n0 = len(cpg_df)
    cpg_df = cpg_df.dropna(subset=[args.pos_col]).copy()
    cpg_df[args.pos_col] = cpg_df[args.pos_col].astype(int)
    print(f"✅ Long table rows: {n0:,} -> {len(cpg_df):,} (after cleaning pos)")
    uniq_sites = cpg_df[[args.chrom_col, args.pos_col]].drop_duplicates().shape[0]
    print(f"✅ Unique sites: {uniq_sites:,}")

    print("\n[3/4] Assign gene for unique sites...")
    cpg_unique = cpg_df[[args.chrom_col, args.pos_col]].drop_duplicates().reset_index(drop=True)
    cpg_unique_with_gene = assign_cpg_to_gene(
        cpg_unique, chrom_to_tss,
        chrom_col=args.chrom_col,
        pos_col=args.pos_col,
        max_distance=args.max_tss_distance
    )

    print("\n[4/4] Merge back to long table + save...")
    merged = pd.merge(
        cpg_df,
        cpg_unique_with_gene[[args.chrom_col, args.pos_col, "gene_id", "gene_name", "dist_to_TSS"]],
        on=[args.chrom_col, args.pos_col],
        how="left"
    )

    merged.to_csv(out_path, index=False, na_rep="NaN")
    print(f"✅ Saved: {out_path}")
    print(f"   rows={len(merged):,} cols={len(merged.columns)}")


if __name__ == "__main__":
    main()